using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using StorageDemo.Infrastructure.Media;

namespace StorageDemo.Tests.Infrastructure;

/// <summary>
/// Runs the real analyzer, which calls libav in this process, against the libraries bundled with
/// the build. The sample media is generated by the bundled ffmpeg command line, so the suite still
/// carries no binary fixtures; that command line is a test convenience and no longer used in the
/// application itself.
/// </summary>
public sealed class LibavMediaAnalyzerTests : IDisposable
{
    private readonly string _directory = Path.Combine(
        Path.GetTempPath(),
        "storage-demo-ffmpeg-tests",
        Guid.NewGuid().ToString("N"));

    public LibavMediaAnalyzerTests() => Directory.CreateDirectory(_directory);

    private static LibavMediaAnalyzer CreateAnalyzer(int thumbnailSize = 320)
        => new(
            Options.Create(new MediaOptions { ThumbnailSize = thumbnailSize, VideoFrameSeconds = 1 }),
            NullLogger<LibavMediaAnalyzer>.Instance);

    [Fact]
    public void The_bundled_libraries_load()
    {
        // Fails loudly if the bindings and the native libraries have drifted apart.
        FfmpegLibrary.EnsureLoaded();

        Assert.True(Directory.Exists(Ffmpeg.Directory), $"Expected bundled FFmpeg at {Ffmpeg.Directory}");
    }

    [Fact]
    public void Pointing_the_library_path_at_a_static_build_is_refused_with_a_reason()
    {
        // A static build's folder holds executables and nothing else. Accepting it would move the
        // failure to the first thumbnail, hours later, as a missing function.
        var staticBuild = Path.Combine(_directory, "static-build");
        Directory.CreateDirectory(staticBuild);
        File.WriteAllText(Path.Combine(staticBuild, "ffmpeg.exe"), "not really");
        File.WriteAllText(Path.Combine(staticBuild, "ffprobe.exe"), "not really");

        var failure = Assert.Throws<FileNotFoundException>(() => Ffmpeg.UseDirectory(staticBuild));

        Assert.Contains("shared", failure.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Pointing_the_library_path_at_a_missing_folder_is_refused()
        => Assert.Throws<DirectoryNotFoundException>(
            () => Ffmpeg.UseDirectory(Path.Combine(_directory, "nowhere")));

    [Fact]
    public void Media_types_are_recognised_and_other_types_are_left_alone()
    {
        var analyzer = CreateAnalyzer();

        Assert.True(analyzer.CanAnalyze("image/png", "photo.png"));
        Assert.True(analyzer.CanAnalyze("video/mp4", "clip.mp4"));
        Assert.True(analyzer.CanAnalyze(null, "clip.mkv"));
        Assert.True(analyzer.CanAnalyze("audio/mpeg", "song.mp3"));

        Assert.False(analyzer.CanAnalyze("text/plain", "notes.txt"));
        Assert.False(analyzer.CanAnalyze("application/pdf", "report.pdf"));

        // ffmpeg cannot rasterise SVG, so claiming it can would produce a broken thumbnail.
        Assert.False(analyzer.CanAnalyze("image/svg+xml", "logo.svg"));
    }

    [Fact]
    public async Task An_image_gets_a_thumbnail_and_its_dimensions()
    {
        var source = await GenerateAsync(
            "still.jpg",
            ["-f", "lavfi", "-i", "testsrc=size=800x600:duration=1:rate=1", "-frames:v", "1"]);

        await using var content = File.OpenRead(source);
        var analysis = await CreateAnalyzer().AnalyzeAsync(content, "still.jpg", "image/jpeg");

        Assert.NotNull(analysis.Thumbnail);
        Assert.True(analysis.Thumbnail.Length > 0);
        Assert.Equal("800 x 600 px", analysis.Metadata["Video dimensions"]);
        Assert.Contains("JPEG", analysis.Metadata["Video codec"], StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task The_thumbnail_is_a_jpeg_scaled_inside_the_configured_box()
    {
        var source = await GenerateAsync(
            "wide.jpg",
            ["-f", "lavfi", "-i", "testsrc=size=1600x400:duration=1:rate=1", "-frames:v", "1"]);

        await using var content = File.OpenRead(source);
        var analysis = await CreateAnalyzer(thumbnailSize: 200).AnalyzeAsync(content, "wide.jpg", "image/jpeg");

        Assert.NotNull(analysis.Thumbnail);

        // JPEG magic number, so the client can trust the declared image/jpeg content type.
        Assert.Equal(0xFF, analysis.Thumbnail[0]);
        Assert.Equal(0xD8, analysis.Thumbnail[1]);

        var (width, height) = await MeasureAsync(analysis.Thumbnail);
        Assert.Equal(200, width);
        Assert.Equal(50, height); // 4:1 preserved rather than squashed into a square.
    }

    [Fact]
    public async Task A_video_gets_a_thumbnail_plus_duration_and_frame_rate()
    {
        var source = await GenerateAsync(
            "clip.avi",
            [
                "-f", "lavfi", "-i", "testsrc=size=320x240:duration=4:rate=25",
                "-c:v", "mjpeg",
            ]);

        await using var content = File.OpenRead(source);
        var analysis = await CreateAnalyzer().AnalyzeAsync(content, "clip.avi", "video/x-msvideo");

        Assert.NotNull(analysis.Thumbnail);
        Assert.True(analysis.Thumbnail.Length > 0);
        Assert.Equal("320 x 240 px", analysis.Metadata["Video dimensions"]);
        Assert.Equal("25 fps", analysis.Metadata["Video frame rate"]);
        Assert.Contains("4", analysis.Metadata["Duration"]);
    }

    [Fact]
    public async Task A_video_shorter_than_the_seek_offset_still_gets_a_thumbnail()
    {
        // The analyzer seeks a second in; this clip ends well before that.
        var source = await GenerateAsync(
            "blink.avi",
            [
                "-f", "lavfi", "-i", "testsrc=size=160x120:duration=0.2:rate=10",
                "-c:v", "mjpeg",
            ]);

        await using var content = File.OpenRead(source);
        var analysis = await CreateAnalyzer().AnalyzeAsync(content, "blink.avi", "video/x-msvideo");

        Assert.NotNull(analysis.Thumbnail);
        Assert.True(analysis.Thumbnail.Length > 0);
    }

    [Fact]
    public async Task A_file_that_is_not_really_media_yields_no_thumbnail_and_no_bogus_dimensions()
    {
        await using var content = new MemoryStream("this is not a png"u8.ToArray());

        var analysis = await CreateAnalyzer().AnalyzeAsync(content, "broken.png", "image/png");

        Assert.Null(analysis.Thumbnail);

        // ffprobe trusts the extension and invents a 0 x 0 stream; that must not reach the user.
        Assert.DoesNotContain("Video dimensions", analysis.Metadata.Keys);
    }

    /// <summary>Builds a sample file with the bundled ffmpeg, so no fixtures live in the repo.</summary>
    private async Task<string> GenerateAsync(string fileName, string[] arguments)
    {
        var path = Path.Combine(_directory, fileName);

        await RunAsync(
            BundledFfmpeg.Tool.Ffmpeg,
            ["-hide_banner", "-loglevel", "error", .. arguments, "-y", path]);

        Assert.True(File.Exists(path), $"ffmpeg did not generate {fileName}");

        return path;
    }

    private async Task<(int Width, int Height)> MeasureAsync(byte[] image)
    {
        var path = Path.Combine(_directory, $"{Guid.NewGuid():N}.jpg");
        await File.WriteAllBytesAsync(path, image);

        var output = await RunAsync(
            BundledFfmpeg.Tool.Ffprobe,
            [
                "-v", "error",
                "-select_streams", "v:0",
                "-show_entries", "stream=width,height",
                "-of", "csv=p=0",
                path,
            ]);

        var parts = output.Trim().Split(',');

        return (int.Parse(parts[0]), int.Parse(parts[1]));
    }

    private static async Task<string> RunAsync(BundledFfmpeg.Tool tool, string[] arguments)
    {
        using var process = BundledFfmpeg.Start(tool, arguments, readOutput: true);
        var output = await process.StandardOutput.ReadToEndAsync();
        await process.WaitForExitAsync();

        // Again, parameterless: the asynchronous wait does not promise that the drained standard
        // error has reached the buffer, and it is the whole failure message.
        process.WaitForExit();

        Assert.True(process.ExitCode == 0, $"{tool} failed: {BundledFfmpeg.Complaints(process)}");

        return output;
    }

    public void Dispose()
    {
        if (Directory.Exists(_directory))
        {
            Directory.Delete(_directory, recursive: true);
        }
    }
}
